services:
  db:
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports: 
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql  # Persistent storage for MySQL database
  back:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: .env
    ports: 
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    environment:
      - DB_HOST= db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: